coquitlam_crawler:
  cron: "0,30 17-23 * * *" # Run every 30 minutes from 5pm until midnight
  class: "Coquitlam::Crawler"
  queue: default
  description: "Collects All Coquitlamd Related data from various RSS Feeds"
