feeds:
  coquitlam:
    - name: "TriCities Dispatch"
      url: "https://tricitiesdispatch.com/category/coquitlam/feed"
      category: "coquitlam"
    - name: "Coquitlam Construction"
      url: "https://www.coquitlam.ca/RSSFeed.aspx?ModID=1&CID=Road-Work-and-Construction-5"
      category: "traffic"
    - name: "TriCity Local News"
      url: "https://www.tricitylocalnews.com/category/tri-cities/feed"
      category: "coquitlam"
      filters: 
        - exclude: 'port coquitlam'
        - include: 'coquitlam'
    - name: "Coquitlam RCMP"
      url: "https://rcmp.ca/en/feed-flux/news-nouvelles/division/e"
      category: "coquitlam"
      filters: 
        - exclude: 'port coquitlam'
        - include: 'coquitlam'
