module Llm
  module Postprocessors
    class Disclaimer
      attr_reader :completed

      def initialize(bluf)
        @completed = add_disclaimer(bluf)
      end

      private

      def add_disclaimer(bluf)
        disclaimer = """
         ### **Disclaimer:**
         The rough draft was generated by an LLM. I did the editing, fact-checking, formatting, and added citations.
         Please understand that I’m not a journalist, just sharing info I think might useful.
         If you spot any mistakes, DM or comment and I’ll fix it and post a correction.
        """

        bluf + disclaimer
      end
    end
  end
end
